{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "junos_exporter.serviceAccountName" . }}
  labels:
{{ include "junos_exporter.labels" . | nindent 4 }}
{{- end -}}
