on:
  push:
    tags:
      - '*.*.*'

name: Docker Build (tag)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: docker
        uses: polygon-io/infra-gh-actions-docker@v1.7.0
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image-repo: ${{ vars.DOCKERHUB_ORGANIZATION_NAME }}/${{ github.event.repository.name }}
          dry-run: ${{ github.event_name == 'pull_request' }}
