on:
  workflow_run:
    workflows: ["Test"]
    branches: [anx-prod]
    types: 
      - completed

name: Deploy and store artifact 
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build .

    - uses: actions/upload-artifact@master
      with:
        name: junos_exporter
        path: junos_exporter

    - uses: actions/upload-artifact@v3
      with:
        name: junos_exporter
        path: ./junos_exporter
